"""
Django settings for docintelligence project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
"""

from pathlib import Path
import os

# BASE_DIR is the root directory of your Django project.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-igt_)a32^l34k3nu_*vh%*q4@!k$0q=p$ah==2ialw75+f56gz'

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS defines a list of host/domain names this Django site can serve.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # '*' allows all hosts (not safe for production)

# Application definition: Register built-in and custom apps here.
INSTALLED_APPS = [
    'django.contrib.admin',                      # Admin interface
    'django.contrib.auth',                       # Authentication framework
    'django.contrib.contenttypes',               # Content type system
    'django.contrib.sessions',                   # Session framework
    'django.contrib.messages',                   # Messaging framework
    'django.contrib.staticfiles',                # Static file management
    'rest_framework',                            # Django REST framework
    'corsheaders',                               # CORS support
    'documents',                                 # Custom app for handling documents
]

# Middleware is a framework of hooks into Django's request/response processing.
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',     # Handles Cross-Origin Resource Sharing
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration module
ROOT_URLCONF = 'docintelligence.urls'

# Template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Directories to search for templates
        'APP_DIRS': True,  # Automatically look for templates inside each app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application entry point
WSGI_APPLICATION = 'docintelligence.wsgi.application'

# Database configuration using MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # Using MySQL database
        'NAME': 'docintelligence_db',           # Database name
        'USER': 'root',                         # DB username
        'PASSWORD': 'Rushi@1',                  # DB password
        'HOST': 'localhost',                    # DB host
        'PORT': '3306',                         # DB port
    }
}

# Password validation settings
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Language and timezone settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True     # Enables Django’s translation system
USE_TZ = True       # Enables timezone-aware datetimes

# Static files (CSS, JS, Images)
STATIC_URL = '/static/'

# Media files (for file uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory where uploaded files are stored

# Default field type for primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',   # Allow unrestricted access (adjust for production)
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',     # Handle JSON requests
        'rest_framework.parsers.MultiPartParser',# Handle file uploads
        'rest_framework.parsers.FormParser',     # Handle form submissions
    ],
}

# CORS policy: Allow all origins (development only)
CORS_ALLOW_ALL_ORIGINS = True

# Logging configuration to print logs to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # Set to INFO or WARNING in production
    },
}
